version: '3'

services:
    db:
     container_name: wp_db
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
     depends_on:
       - db
     container_name: wp_wp
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: wp_db:3306
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

    nginx:
     depends_on:
       - wordpress
     restart: always
     build:
       context: .
       dockerfile: nginx_df
     ports:
       - "80:80"
